version: '3.8'
services:

  homeautomation:
    container_name: homeautomation
    build: homeautomation
    restart: always
    volumes:
      - "/sys:/sys"
      - "/storage/homeautomation/log:/var/log/homeautomation"
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Budapest
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - SPRING_INFLUX_USER=${SPRING_INFLUX_USER}
      - SPRING_INFLUX_PASSWORD=${SPRING_INFLUX_PASSWORD}
      - BEEPER_ENABLED=${BEEPER_ENABLED}
      - BEEPER_PINNUMBER=${BEEPER_PINNUMBER}
      - SUNSETSUNRISE_ZENITH=${SUNSETSUNRISE_ZENITH}
      - SUNSETSUNRISE_LATITUDE=${SUNSETSUNRISE_LATITUDE}
      - SUNSETSUNRISE_LONGITUDE=${SUNSETSUNRISE_LONGITUDE}
      - SUNSETSUNRISE_TIMEZONE=${SUNSETSUNRISE_TIMEZONE}
      - TELEGRAM_BOTTOKEN=${TELEGRAM_BOTTOKEN}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID}

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "/storage/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/storage/mosquitto/config/ps.txt:/mosquitto/config/ps.txt"
      - "/storage/mosquitto/data:/mosquitto/data"
      - "/storage/mosquitto/log:/mosquitto/log"

  influxdb:
    container_name: influxdb
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - "/storage/influxdb:/var/lib/influxdb"
      - "/storage/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    command: -config=/etc/influxdb/influxdb.conf

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    volumes:
      - "/storage/grafana/grafana:/var/lib/grafana"
      - "/storage/grafana/etc:/etc/grafana"
      - "/storage/grafana/log:/var/log/grafana"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - grafana
      - homeautomation

