version: '3'
services:

  homeautomation:
    container_name: homeautomation
    build: homeautomation
    ports:
      - "8080:8080"
    volumes:
      - "/sys:/sys"
      - "/storage/homeautomation/log:/var/log/homeautomation"
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Budapest

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "/storage/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "/storage/mosquitto/config/ps.txt:/mosquitto/config/ps.txt"
      - "/storage/mosquitto/data:/mosquitto/data"
      - "/storage/mosquitto/log:/mosquitto/log"

  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "/storage/influxdb:/var/lib/influxdb"
      - "/storage/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    command: -config=/etc/influxdb/influxdb.conf

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "/storage/grafana/grafana:/var/lib/grafana"
      - "/storage/grafana/etc:/etc/grafana"
      - "/storage/grafana/log:/var/log/grafana"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
